version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/tmp
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run bootstrap
            - run:
                name: Test
                command: npm run test:coverage
                environment:
                  JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            - store_test_results:
                path: ./reports/junit/
            - store_artifacts:
                path: ./coverage/

workflows:
    build-and-test:
      jobs:
        - build-and-test
