version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-lint:
    working_directory: ~/tmp
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run bootstrap
            - run:
                name: Test
                command: npm run test:ci
                environment:
                  JEST_JUNIT_OUTPUT_DIR: ./reports/test/junit/
            - run:
                name: Lint
                command: npm run lint:ci
            - store_test_results:
                path: ./reports/test/junit/
            - store_artifacts:
                path: ./reports

workflows:
    build-test-lint:
      jobs:
        - build-test-lint
