export enum ErrorCodes {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_DID = 'INVALID_DID',
  INVALID_CHALLENGE = 'INVALID_CHALLENGE',
  MAX_REQUESTS_REACHED = 'MAX_REQUESTS_REACHED',
  EXPIRED_ACCESS_TOKEN = 'EXPIRED_ACCESS_TOKEN',
  NO_ACCESS_TOKEN = 'NO_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  UNHANDLED_ERROR = 'UNHANDLED_ERROR',
  UNAUTHORIZED_USER = 'UNAUTHORIZED_USER'
}
