export enum ErrorCodes {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_DID = 'INVALID_DID',
  INVALID_CHALLENGE = 'INVALID_CHALLENGE',
  MAX_REQUESTS_REACHED = 'MAX_REQUESTS_REACHED',
  EXPIRED_ACCESS_TOKEN = 'EXPIRED_ACCESS_TOKEN',
  NO_ACCESS_TOKEN = 'NO_ACCESS_TOKEN',
  NO_REFRESH_TOKEN = 'NO_REFRESH_TOKEN',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  UNHANDLED_ERROR = 'UNHANDLED_ERROR',
  UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
  INVALID_OR_EXPIRED_SESSION = 'INVALID_OR_EXPIRED_SESSION',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  NO_RESPONSE = 'NO_RESPONSE',
  INVALID_HEADER = 'INVALID_HEADER'
}
